# -*- coding: utf-8 -*-
"""Python_UndoRendo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXN6UacI68R0AmKxIb0GQZgmPIejvGyy
"""

import copy

def sh_task(lista_tarefa):
  print()
  print('Tarefas :')
  print(lista_tarefa)
  print()

def add_task(lista_tarefa, aux):
  lista_tarefa.append(input())
  aux.append(copy.deepcopy(lista_tarefa[-1]))

def undo_task(lista_tarefa):
  if len(lista_tarefa) == 0:
      print(f'\nA lista está vazia ! \n')
  else:  
    lista_tarefa.pop()


if __name__ == '__main__':
  lista_tarefa = []
  aux = []
  cont = 0

  while True:
    print('''
    (1)Adicionar Tarefa
    (2)Listar Tarefas
    (3)Desfazer Ação
    (4)Refazer Ação''')
    opc = input((print(f'\nEscolha a opção desejada: \n')))

    if opc == '1': 
      add_task(lista_tarefa,aux)
    elif opc == '2':
      sh_task(lista_tarefa)
    elif opc == '3':
      undo_task(lista_tarefa)
      cont+=1
    elif opc == '4':
      if cont > 0:
        lista_tarefa.append((aux[-cont]))  
        cont-= 1        
      else:
        print(f'\nNenhuma ação foi desfeita!\n')  
    else:
      print(f'\nOpção inválida, tente novamente!\n ')